### ISSUE TITLE
Onappearing is not firing for RGPopup.Maui pages

### ISSUE THREAD

**Issue by sreejithsreenivasan139** [microspaze/RGPopup.Maui#1]
I am using the `RGPopup.Maui` for showing the pop-up pages in my MAUI application.

My problem is onappearing is not firing for RGPopup.Maui pop up pages.

Previously I have used `Rg.Plugins.Popup` in Xamarin Forms, but when I migrate to MAUI I started using the `RGPopup.Maui`. When I open the pop-up page the `onappearing` is not firing, Is it a known issue? Any solutions

I have resolved it by  `overridding` the `OnAppearingAnimationBegin` method.

**Comment by microspaze** [comment]
@sreejithsreenivasan139 You can try the latest version (1.0.2) , I have just fixed this bug.

https://www.nuget.org/packages/RGPopup.Maui/1.0.2
