### ISSUE TITLE
TapGestureRecognizers not working?

### ISSUE THREAD

**Issue by jameslavery** [microspaze/RGPopup.Maui#4]
It seems that TapGestureRecognizers are not working on controls placed in an RGPopup.Maui page.

Adding a TapGestureRecognizer with either a Tapped event or a bound Command does not work - the associated Tapped event handler or Command are not invoked.

Pretty easy to reproduce - just add a TapGestureRecognizer to a control on an RGPopup page. I can provide a reproduction project if needed.

It's quite a problem for me, as I have a custom control with a TapGestureRecognizer which won't work if it's on an RGPopup.Maui page.

This occurs on both Windows (which is what I'm currently developing for) and Android.

**Comment by microspaze** [comment]
@jameslavery I have added two tag gesture demos in RGPopup.Samples project by commit https://github.com/microspaze/RGPopup.Maui/commit/2933eda8551212db948a9868ff99982c2b59c26d
You can pull the code to verify by yourself. It works on both Windows and Android. If YOU CAN UPLOAD A REPRODUCE DEMO PROJECT, I will take a deeper look. Thanks.

**Comment by jameslavery** [comment]
That's interesting, thank you. I will check the samples and if I continue to have a problem, I'll upload a repro project.

**Comment by jameslavery** [comment]
This is odd - my code looks similar to the demo code you've added, but still doesn't work.

I've added a reproduction project to GitHub [here](https://github.com/jameslavery/RGPopupTest) - please take a look when you have a chance.

**Comment by microspaze** [comment]
Your demo prject works for me! Can you rebuild your whole project and try again?

https://github.com/microspaze/RGPopup.Maui/assets/17372096/f4ba8ec1-2830-45d2-af62-ff77c6f0e423

**Comment by microspaze** [comment]
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------------------------
android                    34.0.85/8.0.100        VS 17.10.34707.107, VS 17.9.34622.214
maui-windows               8.0.7/8.0.100          VS 17.10.34707.107, VS 17.9.34622.214
maccatalyst                17.2.8043/8.0.100      VS 17.10.34707.107, VS 17.9.34622.214
ios                        17.2.8043/8.0.100      VS 17.10.34707.107, VS 17.9.34622.214
```

**Comment by jameslavery** [comment]
So I'm slightly behind on maui-windows. I'll try updating and let you know the results. May not be for a day or so though.

**Comment by jameslavery** [comment]
Actually updated my workloads just now (decided risk was low) - this **fixed the problem!**

So there must have been a change in 8.0.7 which fixed it.

Thank you for helping me find a solution!
